apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-node-mem-rules
  namespace: default
spec:
  groups:
    - name: node-mem.rules
      rules:
      - alert: NodeMemoryUsage
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"
        expr: |
          (100 - ( node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 )) >75
        for: 2m
        labels:
          severity: page
      - alert: NodeLowDisk
        annotations:
          summary: "{{$labels.instance}}: Low root disk space"
          description: "{{$labels.instance}}: Root disk usage is above 75% (current value is: {{ $value }})"
        expr: |
          sum(
            max by (device) (
              node_filesystem_size_bytes{job="node-exporter", fstype!=""}
            -
              node_filesystem_avail_bytes{job="node-exporter", fstype!=""}
            )
          )/1024/1024/100 < 20
        for: 2m
        labels:
          severity: page



      - alert: NodeCPUUsage
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
        expr: |
          instance:node_cpu:rate:sum > 75
        for: 2m
        labels:
          severity: page
      - alert: NodeLoadAverage
        annotations:
          summary: "{{$labels.instance}}: High load average detected"
          description: "{{$labels.instance}}: load average is high"
        expr: |
          (node_load5 / count without (cpu, mode) (node_cpu{mode="system"})) > 1
        for: 2m
        labels:
          severity: page

      - alert: high_load
        expr: node_load1 > 0.5
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} is under high load.'
          summary: Instance {{ $labels.instance }} under high load
          value: '{{ $value }}'

      - alert: service_up
        expr: up == 1
        labels:
          service: Platform
          severity: normal
          correlate: service_up,service_down
        annotations:
          description: Service {{ $labels.instance }} is available.
          value: UP ({{ $value }})

      - alert: disk_space
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 5
        labels:
          instance: '{{ $labels.instance }}:{{ $labels.mountpoint }}'
          severity: page


      - alert: disk_util
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes > 5
        labels:
          instance: '{{ $labels.instance }}'





